#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-08-03"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "14a33b40-8947-420c-b230-6c66723fbdca"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://r2.111612.xyz"

[dev]
port = 5000
